// ==============================================================================
// INTEGRATION: AI Triage Fields
// PURPOSE: Adding fields to store the automated risk assessment and recommended
//          actions generated by the Azure OpenAI service.
// ==============================================================================
namespace FieldTechApi.Models;

public class FieldReport
{
    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string LoggedBy { get; set; } = string.Empty;
    public string Status { get; set; } = "Pending"; 
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // New AI Fields
    public string RiskLevel { get; set; } = "Pending Analysis";
    public string AiRecommendedAction { get; set; } = string.Empty;
}